In [1]:
import numpy as np

# Create a NumPy ndarray Object

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


type(): This built-in Python function tells us the type of the object passed to it

In [4]:
print(type(arr))

<class 'numpy.ndarray'>


Use a tuple to create a NumPy array:

In [6]:
arr2 = np.array((1, 2, 3, 4, 5))
print(arr)

[1 2 3 4 5]


# Dimensions in Arrays

0-D Arrays are the elements in an array. Each value in an array is a 0-D array.

In [7]:
arr3 = np.array(42)
print(arr3)

42


1-D Arrays: An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [10]:
arr4 = np.array([1, 2, 3, 4, 5])
print(arr4)

[1 2 3 4 5]


2-D Arrays: An array that has 1-D arrays as its elements is called a 2-D array.

In [12]:
arr5 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr5)

[[1 2 3]
 [4 5 6]]


3-D arrays: An array that has 2-D arrays (matrices) as its elements is called 3-D array.

In [14]:
arr6 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr6)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


# Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [15]:
print(arr3.ndim)
print(arr4.ndim)
print(arr5.ndim)
print(arr6.ndim)

0
1
2
3


# NumPy Array Indexing

Access Array Elements

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [17]:
# Get the first element from the following array
arr7 = np.array([1, 2, 3, 4])
print(arr7[0])

1


In [18]:
# Get the second element from the previous array
print(arr7[1])

2


In [19]:
# Get third and fourth elements from the previous array and add them
print(arr7[2] + arr7[3])

7


Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [20]:
arr8 = np.array([[1, 2, 3, 4 , 5], [6, 7, 8, 9, 10]])
print("2nd element on 1st row: ", arr8[0, 1])

2nd element on 1st row:  2


In [22]:
print('5th element on 2nd row: ', arr8[1, 4])

5th element on 2nd row:  10


Access 3-D Arrays

To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [24]:
arr9 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr9[0, 1, 2])

6


Negative Indexing

Use negative indexing to access an array from the end.

In [26]:
# Print the last element from the 2nd dim
arr10 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('Last element from 2nd dim: ', arr10[1, -1])

Last element from 2nd dim:  10


# NumPy Array Slicing

Slicing arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

In [28]:
# Slice elements from index 1 to index 5 from the following array:
arr11 = np.array([1, 2, 3, 4 ,5 , 6, 7])
print(arr11[1:5])

[2 3 4 5]


In [30]:
# Slice elements from index 4 to the end of the array:
print(arr11[4:])

[5 6 7]


In [31]:
# Slice elements from the beginning to index 4 (not included):
print(arr11[:4])

[1 2 3 4]


Negative Slicing: Use the minus operator to refer to an index from the end:

In [32]:
print(arr11[-3:-1])

[5 6]


In [33]:
print(arr11[1:5:2])

[2 4]


In [35]:
print(arr11[::2])

[1 3 5 7]


Slicing 2-D Arrays

In [36]:
#From the second element, slice elements from index 1 to index 4 (not included):
arr12 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr12[1, 1:4])

[7 8 9]


In [37]:
# From both elements, return index 2:
print(arr12[0:2, 2])

[3 8]


In [38]:
# From both elements, slice index 1 to index 4 (not included):
print(arr12[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


# NumPy Data Types
The NumPy array object has a property called dtype that returns the data type of the array:

In [40]:
a = np.array([1, 2, 3, 4])

print(a.dtype)

int32


In [41]:
b = np.array(['Ahmed', 'Mona', 'Mohammed'])

print(b.dtype)

<U8


# Creating Arrays With a Defined Data Type

In [48]:
c = np.array([1, 2, 3, 4], dtype='S')
print(c)
print(c.dtype)

[b'1' b'2' b'3' b'4']
|S1


# What if a Value Can Not Be Converted?
If a type is given in which elements can't be casted then NumPy will raise a ValueError.

In [45]:
# A non integer string like 'a' can not be converted to integer (will raise an error):
d = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

# Converting Data Type on Existing Arrays
The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

In [46]:
e = np.array([1.1, 2.1, 3.1])
newe = arr.astype('i')

print(newe)
print(newe.dtype)

[1 2 3 4]
int32


# NumPy Array Copy vs View
The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

In [49]:
f = np.array([1, 2, 3, 4, 5])
g = f.copy()

In [50]:
print(f)
print(g)

[1 2 3 4 5]
[1 2 3 4 5]


In [51]:
f[0] = 44

In [52]:
print(f)
print(g)

[44  2  3  4  5]
[1 2 3 4 5]


In [55]:
h = np.array([11, 22, 33, 44])
i = h.view()

In [56]:
print(h)
print(i)

[11 22 33 44]
[11 22 33 44]


In [57]:
h[0] = 111

In [59]:
print(h)
print(i)

[111  22  33  44]
[111  22  33  44]


# NumPy Array Shape
The shape of an array is the number of elements in each dimension.

In [60]:
j = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(j.shape)

(2, 4)


# NumPy Array Reshaping
Reshaping means changing the shape of an array.

In [6]:
k = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newk1 = k.reshape(4, 3)

In [7]:
print(newk1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Reshape From 1-D to 3-D

In [8]:
newk2 = k.reshape(2, 3, 2)

In [9]:
print(newk2)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# Can We Reshape Into any Shape?

In [11]:
l = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newl = l.reshape(3, 3)

ValueError: cannot reshape array of size 8 into shape (3,3)

# Unknown Dimension
You are allowed to have one "unknown" dimension.

Pass -1 as the value, and NumPy will calculate this number for you.

Note: We can not pass -1 to more than one dimension.

In [12]:
newl = l.reshape(2, 2, -1)

In [13]:
print(newl)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [14]:
m = np.array([[1, 2, 3], [4, 5, 6]])

In [16]:
newm = m.reshape(-1)
print(newm)

[1 2 3 4 5 6]


# NumPy Array Iterating
Iterating means going through elements one by one.

In [17]:
# Iterate on the elements of the following 1-D array:
n = np.array([1, 2, 3])

for x in n:
    print(x)

1
2
3


In [19]:
# Iterate on the elements of the following 2-D array:
o = np.array([[1, 2, 3], [4, 5, 6]])

for x in o:
    for y in x:
        print(y)

1
2
3
4
5
6


In [20]:
# Iterate on the elements of the following 3-D array:
p = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in p:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterating Arrays Using nditer()

In [21]:
q = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(q):
    print(x)

1
2
3
4
5
6
7
8


# Iterating With Different Step Size

In [22]:
r = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(r[:, ::2]):
    print(x)

1
3
5
7


# NumPy Joining Array
Joining means putting contents of two or more arrays in a single array.

In [25]:
# Join two arrays
s1 = np.array([1, 2, 3])
s2 = np.array([4, 5, 6])
s = np.concatenate((s1, s2))

In [26]:
print(s)

[1 2 3 4 5 6]


In [31]:
# Join two 2-D arrays along rows (axis=1):
t1 = np.array([[1, 2], [3, 4]])
t2 = np.array([[5, 6], [7, 8]])

t = np.concatenate((t1, t2), axis=1)

In [32]:
print(t)

[[1 2 5 6]
 [3 4 7 8]]


# Joining Arrays Using Stack Functions

In [33]:
s = np.stack((s1, s2), axis=1)
print(s)

[[1 4]
 [2 5]
 [3 6]]


NumPy provides a helper function: hstack() to stack along rows.

In [34]:
s = np.hstack((s1, s2))
print(s)

[1 2 3 4 5 6]


NumPy provides a helper function: vstack()  to stack along columns.

In [36]:
s = np.vstack((s1, s2))
print(s)

[[1 2 3]
 [4 5 6]]


NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [37]:
s = np.dstack((s1, s2))
print(s)

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting NumPy Arrays
Splitting is reverse operation of Joining.

In [40]:
# Split the array in 3 parts:
u = np.array([1, 2, 3, 4, 5, 6])
newu1 = np.array_split(u, 3)

In [41]:
print(newu1)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [44]:
newu2 = np.array_split(u, 4)

In [45]:
print(newu2)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [46]:
print(newu2[0])
print(newu2[1])
print(newu2[2])

[1 2]
[3 4]
[5]


# Splitting 2-D Arrays

In [48]:
# Split the 2-D array into three 2-D arrays.
v = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newv = np.array_split(v, 3)

In [49]:
print(newv)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [52]:
# Split the 2-D array into three 2-D arrays.
w = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
neww1 = np.array_split(w, 3)

In [53]:
print(neww1)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [54]:
# Split the 2-D array into three 2-D arrays along rows.
neww2 = np.array_split(w, 3, axis=1)

In [56]:
print(neww2)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# NumPy Searching Arrays

In [2]:
x = np.array([1, 2, 3, 4, 5, 4, 4])
y = np.where(x == 4)
print(y)

(array([3, 5, 6], dtype=int64),)


In [3]:
z = np.array([1, 2, 3, 4, 5, 6, 7, 8])
z1 = np.where(z % 2 == 0)
print(z1)

(array([1, 3, 5, 7], dtype=int64),)


# NumPy Sorting Arrays

In [4]:
A = np.array([3, 2, 0, 1])
print(np.sort(A))

[0 1 2 3]


In [5]:
B = np.array(['banana', 'cherry', 'apple'])
print(np.sort(B))

['apple' 'banana' 'cherry']


Sorting a 2-D Array

In [6]:
C = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(C))

[[2 3 4]
 [0 1 5]]


# Simple Arithmetic

# - Addition
The add() function sums the content of two arrays, and return the results in a new array.

In [4]:
D1 = np.array([10, 11, 12, 13, 14, 15])
D2 = np.array([20, 21, 22, 23, 24, 25])

newD1 = np.add(D1, D2)

In [5]:
print(newD1)

[30 32 34 36 38 40]


# - Subtraction
The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.

In [6]:
newD2 = np.subtract(D1, D2)

In [7]:
print(newD2)

[-10 -10 -10 -10 -10 -10]


# - Multiplication
The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.

In [8]:
newD3 = np.multiply(D1, D2)

In [9]:
print(newD3)

[200 231 264 299 336 375]


# - Division
The divide() function divides the values from one array with the values from another array, and return the results in a new array.

In [12]:
E1 = np.array([10, 20, 30, 40, 50, 60])
E2 = np.array([3, 5, 10, 8, 2, 33])

newE1 = np.divide(E1, E2)

In [13]:
print(newE1)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


# - Power
The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

In [14]:
newE2 = np.power(E1, E2)

In [15]:
print(newE2)

[      1000    3200000  716276736 -520093696       2500          0]


# - Remainder
Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

In [16]:
newE3 = np.mod(E1, E2)

In [17]:
print(newE3)

[ 1  0  0  0  0 27]


In [19]:
newE4 = np.remainder(E1, E2)

In [20]:
print(newE4)

[ 1  0  0  0  0 27]


# - Quotient and Mod
The divmod() function return both the quotient and the the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [21]:
newE5 = np.divmod(E1, E2)

In [22]:
print(newE5)

(array([ 3,  4,  3,  5, 25,  1], dtype=int32), array([ 1,  0,  0,  0,  0, 27], dtype=int32))


# - Absolute Values
Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

In [23]:
F = np.array([-1, -2, 1, 2, 3, -4])
newF = np.absolute(F)

In [24]:
print(newF)

[1 2 1 2 3 4]


# Rounding Decimals

# - Truncation
emove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

In [27]:
G1 = np.trunc([-3.1666, 3.6667])

In [28]:
print(G1)

[-3.  3.]


In [29]:
G2 = np.fix([-3.1666, 3.6667])

In [30]:
print(G2)

[-3.  3.]


# - Rounding
The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

E.g. round off to 1 decimal point, 3.16666 is 3.2

In [33]:
# Round off 3.1666 to 2 decimal places:
H = np.around(3.1666, 2)

In [34]:
print(H)

3.17


# - Floor
The floor() function rounds off decimal to nearest lower integer.

E.g. floor of 3.166 is 3.

In [35]:
I = np.floor([-3.1666, 3.6667])

In [36]:
print(I)

[-4.  3.]


# - Ceil
 The ceil() function rounds off decimal to nearest upper integer.

E.g. ceil of 3.166 is 4.

In [37]:
J = np.ceil([-3.1666, 3.6667])

In [38]:
print(J)

[-3.  4.]


# NumPy Logs

# - Log at Base 2
Use the log2() function to perform log at the base 2.

In [39]:
K = np.arange(1, 10)

print(np.log2(K))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


# - Log at Base 10
Use the log10() function to perform log at the base 10.

In [40]:
print(np.log10(K))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


# - Natural Log, or Log at Base e
Use the log() function to perform log at the base e.

In [42]:
L = np.arange(1, 10)

print(np.log(L))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


# - Log at Any Base
NumPy does not provide any function to take log at any base, so we can use the frompyfunc() function along with inbuilt function math.log() with two input parameters and one output parameter:

In [43]:
from math import log

In [44]:
nplog = np.frompyfunc(log, 2, 1)

In [45]:
print(nplog(100, 15))

1.7005483074552052


# Summations
What is the difference between summation and addition?

Addition is done between two arguments whereas summation happens over n elements.

In [49]:
M1 = np.array([1, 2, 3])
M2 = np.array([1, 2, 3])

newM1 = np.add(M1, M2)

In [50]:
print(newM1)

[2 4 6]


In [51]:
newM2 = np.sum([M1, M2])

In [52]:
print(newM2)

12


# Summation Over an Axis
If you specify axis=1, NumPy will sum the numbers in each array.

In [53]:
newM3 = np.sum([M1, M2], axis=1)

In [54]:
print(newM3)

[6 6]


# Cummulative Sum
Cummulative sum means partially adding the elements in array.

E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].

In [56]:
N = np.array([1, 2, 3])

newN = np.cumsum(N)

In [57]:
print(newN)

[1 3 6]


# NumPy Products
To find the product of the elements in an array, use the prod() function.

In [60]:
# Find the product of the elements of this array:
O = np.array([1, 2, 3, 4])

P = np.prod(O)

In [61]:
print(P)

24


In [62]:
# Find the product of the elements of two arrays:
Q1 = np.array([1, 2, 3, 4])
Q2 = np.array([5, 6, 7, 8])

Q = np.prod([Q1, Q2])

In [63]:
print(Q)

40320


# Product Over an Axis
If you specify axis=1, NumPy will return the product of each array.

In [66]:
R1 = np.array([1, 2, 3, 4])
R2 = np.array([5, 6, 7, 8])

newR = np.prod([R1, R2], axis=1)

In [67]:
print(newR)

[  24 1680]


# Cummulative Product
Cummulative product means taking the product partially.

E.g. The partial product of [1, 2, 3, 4] is [1, 1*2, 1*2*3, 1*2*3*4] = [1, 2, 6, 24]

In [68]:
S = np.array([5, 6, 7, 8])

newS = np.cumprod(S)

In [69]:
print(newS)

[   5   30  210 1680]


# NumPy Differences

A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

In [72]:
T = np.array([10, 15, 25, 5])

newT1 = np.diff(T)

In [73]:
print(newT1)

[  5  10 -20]


We can perform this operation repeatedly by giving parameter n.

E.g. for [1, 2, 3, 4], the discrete difference with n = 2 would be [2-1, 3-2, 4-3] = [1, 1, 1] , then, since n=2, we will do it once more, with the new result: [1-1, 1-1] = [0, 0]

In [80]:
newT2 = np.diff(T, n=2)

In [81]:
print(newT2)

[  5 -30]
